[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"
  functions = "functions"  # Remova se não usar serverless functions

[dev]
  framework = "vite"
  target = "static"
  port = 5173

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
