[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"  # Verifique se 'dist' é o diretório correto do seu build
  # Remova a linha abaixo se você não estiver usando funções serverless
  functions = "functions"  

[dev]
  framework = "vite"
  target = "static"
  port = 5173

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
